"""Порты персистентности: чаты, пользователи, документы."""

from __future__ import annotations

from typing import Protocol

from app.domain.chat import Chat, ChatMessage
from app.domain.document import Document, DocumentStatus
from app.domain.user import User


class ChatRepository(Protocol):
    async def create_chat(self, user_id: str, title: str) -> Chat: ...
    async def list_chats(self, user_id: str) -> list[Chat]: ...
    async def get_chat(self, chat_id: str, user_id: str) -> Chat | None: ...
    async def rename_chat(
        self, chat_id: str, user_id: str, title: str
    ) -> Chat | None: ...
    async def delete_chat(self, chat_id: str, user_id: str) -> bool: ...
    async def add_message(self, message: ChatMessage) -> ChatMessage: ...
    async def list_messages(
        self, chat_id: str, user_id: str, limit: int = 100
    ) -> list[ChatMessage]: ...


class UserRepository(Protocol):
    async def create(self, email: str, hashed_password: str) -> User: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_id(self, user_id: str) -> User | None: ...


class DocumentRepository(Protocol):
    async def create(self, document: Document) -> Document: ...
    async def get(self, doc_id: str, user_id: str) -> Document | None: ...
    async def list(self, user_id: str) -> list[Document]: ...
    async def set_status(
        self,
        doc_id: str,
        status: DocumentStatus,
        error: str | None = None,
    ) -> None: ...
    async def set_hash(self, doc_id: str, digest: str) -> None: ...
    async def delete(self, doc_id: str, user_id: str) -> bool: ...
